package com.publicmaders.android.chessopeningsquiz

class OpeningManager
{
    val openings = mutableListOf<Opening>()

    init{
        openings.add(Opening("Alekhine’s Defense","1.e4 Nf6"))
        openings.add(Opening("Alekhine’s Defense Modern Variation","1.e4 Nf6 2.e5 Nd5 3.d4 d6 4.Nf3"))
        openings.add(Opening("Benko Gambit","1.d4 Nf6 2.c4 c5 3.d5 b5"))
        openings.add(Opening("Benko Gambit Accepted","1.d4 Nf6 2.c4 c5 3.d5 b5 cxb5"))
        openings.add(Opening("Benoni Defense","1.e4 Nf6"))
        openings.add(Opening("Benoni Defense Modern Variation","1.d4 Nf6 2.c4 c5 3.d5 e6"))
        openings.add(Opening("Bird’s Opening","1.f4"))
        openings.add(Opening("Bird’s Opening Dutch Variation","1.f4 d5 3.Nf3"))
        openings.add(Opening("Bogo-Indian defense","1.d4 Nf6 2.c4 e6 3.Nf3 Bb4+"))
        openings.add(Opening("Bogo-Indian Defense Nimzowitsch Variation","1.d4 Nf6 2.c4 e6 3.Nf3 Bb4+ 4.Bd2 Qe7"))
        openings.add(Opening("Budapest Gambit","1.d4 Nf6 2.c4 e5"))
        openings.add(Opening("Budapest Gambit Rubinstein Variation","1.d4 Nf6 2.c4 e5 3.dxe5 Ng4 4.Bf4 Nc6"))
        openings.add(Opening("Catalan Opening","1.d4 Nf6 2.c4 e6 3.g3"))
        openings.add(Opening("Catalan Opening Open Defense","1.d4 Nf6 2.c4 e6 3.g3 e6 4.Nc3 dxc4 5.Bg2"))
        openings.add(Opening("Caro-Kann Defense","1.e4 c6"))
        openings.add(Opening("Caro-Kann Defense Advance Variation","1.e4 c6 2.e5 Bf5"))
        openings.add(Opening("Colle System","1.d4 d5 2.Nf3 Nf6 3.e3"))
        openings.add(Opening("Dutch Defense","1.d4 f5"))
        openings.add(Opening("Dutch Defense Fianchetto Attack","1.d4 f5 2.g3 Nf6"))
        openings.add(Opening("English Opening","1.c4"))
        openings.add(Opening("English Opening Anglo-Indian Defense","1.c4 Nf6"))
        openings.add(Opening("Evans Gambit","1.e4 e5 2.Nf3 Nc6 3.Bc4 Bc5 4.b4"))
        openings.add(Opening("Evans Gambit Accepted","1.e4 e5 2.Nf3 Nc6 3.Bc4 Bc5 4.b4 Bxb4 c3"))
        openings.add(Opening("Four Knights Game","1.e4 e5 2.Nf3 Nc6 3.Nc3 Nf6"))
        openings.add(Opening("Four Knights Game Double Spanish Variation","1.e4 e5 2.Nf3 Nc6 3.Nc3 Nf6 4.Bb5 Bb4"))
        openings.add(Opening("French Defense","1.e4 e6"))
        openings.add(Opening("French Defense Winawer Variation","1.e4 e6 2.d4 d5 3.Nc3 Bb4"))
        openings.add(Opening("Giuoco Piano","1.e4 e5 2.Nf3 Nc6 3.Bc4 Bc5"))
        openings.add(Opening("Giuoco Piano Classical Variation","1.e4 e5 2.Nf3 Nc6 3.Bc4 Bc5 4.c3 Nf6"))
        openings.add(Opening("Grünfeld Defense","1.d4 Nf6 2.c4 g6 3.Nc3 d5"))
        openings.add(Opening("Grünfeld Defense Exchange Variation","1.d4 Nf6 2.c4 g6 3.Nc3 d5 4.cxd5 Nxd5"))
        openings.add(Opening("Italian Game","1.e4 e5 2.Nf3 Nc6 3.Bc4"))
        openings.add(Opening("Italian Game Giuoco Pianissimo","1.e4 e5 2.Nf3 Nc6 3.Bc4 Bc5 4.0-0 Nf6 5.d3"))
        openings.add(Opening("King’s Gambit","1.e4 e5 2.f4"))
        openings.add(Opening("King’s Gambit Accepted","1.e4 e5 2.f4 exf4"))
        openings.add(Opening("King’s Indian Attack","1.Nf3 d5 2.g3"))
        openings.add(Opening("King’s Indian Attack Yugoslav Variation","1.Nf3 d5 2.g3 Nf6 3.Bg2 c6 4.O-O Bg4 5.d3 Nbd7 6.Nbd2 e5 7.e4"))
        openings.add(Opening("King’s Indian Defense","1.d4 Nf6 2.c4 g6"))
        openings.add(Opening("London System","1.d4 Nf6 2.Nf3 d5 3.Bc4"))
        openings.add(Opening("Modern Defense","1.d4 g6"))
        openings.add(Opening("Modern Defense Standard Line","1.d4 g6 2.e4 d6 3.Nc3 Bg7"))
        openings.add(Opening("Nimzo-Indian Defense","1.d4 Nf6 2.c4 e6 3.Nc3 Bb4"))
        openings.add(Opening("Nimzo-Indian Defense Rubinstein Variation","1.d4 Nf6 2.c4 e6 3.Nc3 Bb4 4.e3 0-0 5.Bd3 d5"))
        openings.add(Opening("Nimzowitsch Defense","1.e4 Nc6"))
        openings.add(Opening("Nimzowitsch Defense Scandinavian Variation","1.e4 Nc6 2.d4 d5"))
        openings.add(Opening("Petrov’s Defense","1.e4 e5 2.Nf3 Nf6"))
        openings.add(Opening("Petrov’s Defense Classical Variation","1.e4 e5 2.Nf3 Nf6 3.Nxe5 d6"))
        openings.add(Opening("Philidor’s Defense","1.e4 e5 2.Nf3 d6"))
        openings.add(Opening("Philidor’s Defense Exchange Variation","1.e4 e5 2.Nf3 d6 3.d4 exd4"))
        openings.add(Opening("Pirc Defense","1.e4 d6 2.d4 Nf6"))
        openings.add(Opening("Pirc Defense Classical Variation","1.e4 d6 2.d4 Nf6 3.Nc3 g6 4.Nf3 Bg7 5.Be2 O-O 6.O-O c6"))
        openings.add(Opening("Queen’s Gambit","1.d4 d5 2.c4"))
        openings.add(Opening("Queen’s Gambit Accepted","1.d4 d5 2.c4 dxc4"))
        openings.add(Opening("Queen’s Gambit Accepted Main Line","1.d4 d5 2.c4 dxc4 3.Nf3 Nf6 4.d3"))
        openings.add(Opening("Queen’s Gambit Declined","1.d4 d5 2.c4 e6"))
        openings.add(Opening("Queen’s Gambit Declined Semi Slav Variation","1.d4 d5 2.c4 e6 3. Nf3 Nf6 4.Nc3 c6"))
        openings.add(Opening("Queen’s Indian Defense","1.d4 Nf6 2.c4 e6 3.Nf3 b6"))
        openings.add(Opening("Queen’s Indian Defense Fianchetto Variation","1.d4 Nf6 2.c4 e6 3.Nf3 b6 4.g3 Ba6"))
        openings.add(Opening("Queen’s Pawn Game","1.d4"))
        openings.add(Opening("Queen’s Pawn Game / Anti-Nimzo-Indian","1.d4 Nf6 2.c4 e6 3.Nf3"))
        openings.add(Opening("Réti Opening / Queen’s Gambit Declined (Transposed)","1.Nf3 d5 2.c4 e6"))
        openings.add(Opening("Réti Opening","1.Nf3 d5 2.c4"))
        openings.add(Opening("Ruy Lopez","1.e4 e5 2.Nf3 Nc6 3.Bb5"))
        openings.add(Opening("Ruy Lopez Closed Defense","1.e4 e5 2.Nf3 Nc6 3.Bb5 a6 4.Ba4"))
        openings.add(Opening("Scandinavian Defense","1.e4 d5"))
        openings.add(Opening("Scandinavian Defense Main Line","1.e4 d5 2.exd5 Qxd5 3.Nc3 Qa5"))
        openings.add(Opening("Scotch Game","1.e4 e5 2.Nf3 Nc6 3.d4"))
        openings.add(Opening("Scotch Game Classical Variation","1.e4 e5 2.Nf3 Nc6 3.d4 exd4 4.Nxd5 Bc5 5.Be3"))
        openings.add(Opening("Sicilian Defense","1.e4 c5"))
        openings.add(Opening("Sicilian Defense Najdorf Variation","1.e4 c5 2.Nf3 d6 3.d4 cxd4 4.Nxd4 Nf6 5.Nc3 a6"))
        openings.add(Opening("Slav Defense","1.d4 d5 2.c4 c6"))
        openings.add(Opening("Slav Defense Modern Line","1.d4 d5 2.c4 c6 3.Nf3 Nf6"))
        openings.add(Opening("Torre Attack","1.d4 e6 2.Nf3 Nf6 3.Bg5"))
        openings.add(Opening("Two Knights Defense","1.e4 e5 2.Nf3 Nc6 3.Bc4 Nf6"))
        openings.add(Opening("Fried Liver Attack","1.e4 e5 2.Nf3 Nc6 3.Bc4 Nc6 4.Ng5"))
        openings.add(Opening("Two Knights Defense / Giuoco Pianissimo (Transposed)","1.e4 e5 2.Nf3 Nc6 3.Bc4 Nf6 4.d3 Bc5"))
        openings.add(Opening("Vienna Game","1.e4 e5 2.Nc3"))
        openings.add(Opening("Vienna Game Mieses Variation","1.e4 e5 2.Nc3 Nf6 3.g3"))
        openings.add(Opening("Wade Defense","1.d4 d6 2.Nf3 Bg4"))
        openings.add(Opening("Wade Defense Main Line","1.d4 d6 2.Nf3 Bg4 3.c4 Nbd7 4.Nc3 e5"))
    }
}